name: Super Cool Workflow
on: push
env:
  continent: "Europe"
jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    env:
      country: "Germany"
    steps:
      - name: Step-1
        run: |
          export country="France"
          echo "I am in $city, $country, $continent"
        env:
          city: "Berlin"
      - name: Step-2
        run: echo "I am in $city, $country, $continent"
        env:
          city: "Munich"
