name: Super Cool Workflow
on: push
jobs:
  cool_first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple echo command
        run: |
          sum_var = 2+2
          for _ in range(10):
            print(f"Sum of 2 and 2 is {sum_var}")
        shell: python