name: Super Cool Workflow
on: push 
jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple command
        run: |
          Get-Location
          Write-Host "So cool" -ForegroundColor DarkGreen
        shell: pwsh