name: Super Cool Workflow
on: push
env:
  continent: Europe
jobs:
  cool_first_job:
    env:
      country: Germany
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        env:
          city: Berlin
        run: echo "I am in $city, $country, $continent"
      - name: Step-1
        run: echo "I am in $city, $country, $continent"
