name: Super Cool Workflow
on: push
jobs:
  cool_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple echo command
        run: echo "Wow! I am able to echo from Github"
      - name: Run python command
        run: print(f"Sum of 2 and 2 is {2+2}")
        shell: python